services: 
  landing:
    build: .
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=pgdatabase
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nyc_taxi
    volumes:
      - /landing:/app/landing
    depends_on:
      - pgdatabase
    networks:
      - app-network
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nyc_taxi
    volumes: 
      - /landing/ny_taxi_postgers_data:/var/lib/postgresql/data:rw
    ports: 
    - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge