services: 
  postgres:
    image: postgres:13
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nyc_taxi
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports: 
    - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 3
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    restart: always
  landing:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nyc_taxi
      - TABLE_NAME=yellow_taxi_trip
    volumes:
      - ./landing:/app/landing
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local